### ISSUE TITLE
Need Simplified Chinese Support

### ISSUE THREAD

**Issue by ruby109** [JamienAU/RandomHearth#5]
![image](https://github.com/user-attachments/assets/3e7e1d8a-7adc-4339-a51d-5bccf572cb03)
All Simplified Chinese cannot be showed correctly

**Comment by nanjuekaien1** [comment]
建个Fonts文件夹里面创建个命名：FRIZQT__.TTF 的字体文件就显示了。

**Comment by BlueNightSky** [comment]
這插件指定的字体問題，把"Fonts\\FRIZQT__.TTF"替代為Fonts\\ARKai_T.TTF"就解決了，或是：
I suggest replacing the following code："Fonts\\FRIZQT__.TTF" to STANDARD_TEXT_FONT

**Comment by nanjuekaien1** [comment]
@BlueNightSky  TrueStatValues有人修复了我发在NGA帖子内了

**Comment by JamienAU** [comment]
> 這插件指定的字体問題，把"Fonts\FRIZQT__.TTF"替代為Fonts\ARKai_T.TTF"就解決了，或是： I suggest replacing the following code："Fonts\FRIZQT__.TTF" to STANDARD_TEXT_FONT

Thanks, I have updated to 'STANDARD_TEXT_FONT' and it should now show:

![image](https://github.com/user-attachments/assets/b5418e08-3945-496d-a0c5-a62424b2d99e)
