### ISSUE TITLE
The random macro icon seems to have no effect

### ISSUE THREAD

**Issue by BlueNightSky** [JamienAU/RandomHearth#6]
The random macro icon seems to have no effect. Only when you reload or log in next time, the icon will change.

**Comment by JamienAU** [comment]
That is correct. The macro icon will update when you log in, or when your UI loads.
The function to update the macro doesn't seem to work correctly if you click the button quickly, it sends messages in chat:
![image](https://github.com/user-attachments/assets/feee42c6-bb8f-4b31-8d3b-862cb67949d0)

I haven't been able to figure out why it does this, so I have removed updating the macro on click for now

**Comment by JamienAU** [comment]
It turns out that I can update the macro without setting text. This avoids that issue in my message above.
I have pushed the update and will upload to CurseForge with the fix for CN text not loading.

**Comment by BlueNightSky** [comment]
The latest r17 version has been repaired, thanks!
